#ifndef __CONST_MENU_CHOSE_SETTING_UVV__
#define __CONST_MENU_CHOSE_SETTING_UVV__

#define EKRAN_CHOOSE_SETTINGS_UVV        (EKRAN_CONTROL_SWITCH + 1)
#define EKRAN_DOPUSK_DV_UVV              (EKRAN_CHOOSE_SETTINGS_UVV + 1)
#define EKRAN_TYPE_INPUT_UVV             (EKRAN_DOPUSK_DV_UVV + 1)
#define EKRAN_TYPE_INPUT_SIGNAL_UVV      (EKRAN_TYPE_INPUT_UVV + 1)
#define EKRAN_TYPE_OUTPUT_UVV            (EKRAN_TYPE_INPUT_SIGNAL_UVV + 1)
#define EKRAN_TYPE_LED_UVV               (EKRAN_TYPE_OUTPUT_UVV + 1)

#define MAX_ROW_FOR_CHOSE_SETTINGS_UVV   5

#define INDEX_ML_UVV_DOPUSKT             0
#define INDEX_ML_UVV_TYPE_INPUT          1
#define INDEX_ML_UVV_TYPE_INPUT_SIGNAL   2
#define INDEX_ML_UVV_TYPE_OUTPUT         3
#define INDEX_ML_UVV_TYPE_LED            4

#define COL_DOPUSK_DV_BEGIN              5
#define COL_DOPUSK_DV_END                6


#endif
