#ifndef __CONSTANTS_OUTPUTS__
#define __CONSTANTS_OUTPUTS__

#define EKRAN_LIST_OUTPUTS_FOR_RANGUVANNJA        (EKRAN_LIST_INPUTS_FOR_RANGUVANNJA + 1)

#define EKRAN_RANGUVANNJA_OUTPUT_1                (EKRAN_RANGUVANNJA_INPUT_10 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_2                (EKRAN_RANGUVANNJA_OUTPUT_1 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_3                (EKRAN_RANGUVANNJA_OUTPUT_2 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_4                (EKRAN_RANGUVANNJA_OUTPUT_3 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_5                (EKRAN_RANGUVANNJA_OUTPUT_4 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_6                (EKRAN_RANGUVANNJA_OUTPUT_5 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_7                (EKRAN_RANGUVANNJA_OUTPUT_6 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_8                (EKRAN_RANGUVANNJA_OUTPUT_7 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_9                (EKRAN_RANGUVANNJA_OUTPUT_8 + 1)
#define EKRAN_RANGUVANNJA_OUTPUT_10               (EKRAN_RANGUVANNJA_OUTPUT_9 + 1)

#define MAX_ROW_LIST_OUTPUTS_FOR_RANGUVANNJA       NUMBER_OUTPUTS
#define MAX_ROW_RANGUVANNJA_OUTPUT                 NUMBER_TOTAL_SIGNAL_FOR_RANG_OUTPUT_LED_DF_REG



#endif 
