#ifndef __CONSTANTS_LEDS__
#define __CONSTANTS_LEDS__

#define EKRAN_LIST_LEDS_FOR_RANGUVANNJA        (EKRAN_LIST_OUTPUTS_FOR_RANGUVANNJA + 1)

#define EKRAN_RANGUVANNJA_LED_1                (EKRAN_RANGUVANNJA_OUTPUT_10 + 1)
#define EKRAN_RANGUVANNJA_LED_2                (EKRAN_RANGUVANNJA_LED_1 + 1)
#define EKRAN_RANGUVANNJA_LED_3                (EKRAN_RANGUVANNJA_LED_2 + 1)
#define EKRAN_RANGUVANNJA_LED_4                (EKRAN_RANGUVANNJA_LED_3 + 1)
#define EKRAN_RANGUVANNJA_LED_5                (EKRAN_RANGUVANNJA_LED_4 + 1)
#define EKRAN_RANGUVANNJA_LED_6                (EKRAN_RANGUVANNJA_LED_5 + 1)
#define EKRAN_RANGUVANNJA_LED_7                (EKRAN_RANGUVANNJA_LED_6 + 1)
#define EKRAN_RANGUVANNJA_LED_8                (EKRAN_RANGUVANNJA_LED_7 + 1)


#define MAX_ROW_LIST_LEDS_FOR_RANGUVANNJA       NUMBER_LEDS
#define MAX_ROW_RANGUVANNJA_LED                 NUMBER_TOTAL_SIGNAL_FOR_RANG_OUTPUT_LED_DF_REG

#endif 
