#ifndef __CONSTANTS_BUTTONS__
#define __CONSTANTS_BUTTONS__

#define EKRAN_LIST_BUTTONS_FOR_RANGUVANNJA        (EKRAN_RANGUVANNJA_RESET_DT4_MINUS + 1)

#define EKRAN_RANGUVANNJA_BUTTON_1                (EKRAN_LIST_BUTTONS_FOR_RANGUVANNJA + 1)
#define EKRAN_RANGUVANNJA_BUTTON_2                (EKRAN_RANGUVANNJA_BUTTON_1 + 1)
#define EKRAN_RANGUVANNJA_BUTTON_3                (EKRAN_RANGUVANNJA_BUTTON_2 + 1)
#define EKRAN_RANGUVANNJA_BUTTON_4                (EKRAN_RANGUVANNJA_BUTTON_3 + 1)
#define EKRAN_RANGUVANNJA_BUTTON_5                (EKRAN_RANGUVANNJA_BUTTON_4 + 1)
#define EKRAN_RANGUVANNJA_BUTTON_6                (EKRAN_RANGUVANNJA_BUTTON_5 + 1)

#define MAX_ROW_LIST_BUTTONS_FOR_RANGUVANNJA       NUMBER_DEFINED_BUTTONS
#define MAX_ROW_RANGUVANNJA_BUTTON                 NUMBER_TOTAL_SIGNAL_FOR_RANG_BUTTON

#endif 
